spring:
  application:
    name: ISHLT
  profiles:
    active: dev

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: NONE
    banner: false # 关闭控制台的 Banner 打印
  type-aliases-package: com.orange.ishlt.dal.dataobject

mybatis-plus-join:
  banner: false # 关闭控制台的 Banner 打印

# 日志文件配置
logging:
  file:
    name: /data/logs/${spring.application.name}.log # 日志文件名，全路径
  level:
    # 配置自己写的 MyBatis Mapper 打印日志
    com.orange.ishlt: debug
    org.elasticsearch.client: debug

debug: false
