server:
  port: 8080

spring:
  datasource:
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        allow: # 设置白名单，不填则允许所有访问
        url-pattern: /druid/*
        login-username: # 控制台管理用户名和密码
        login-password:
      filter:
        stat:
          enabled: true
          log-slow-sql: true # 慢 SQL 记录
          slow-sql-millis: 300
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
      url: jdbc:mysql://192.168.2.212:3307/ishlt?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
      username: root
      password: tbl_db_543
      driver-class-name: com.mysql.cj.jdbc.Driver
